#!/usr/bin/env bash
# =============================================================================
# 04_create_warehouse_and_get_dbt_creds.sh
# -----------------------------------------------------------------------------
# IMPORTANT ARCHITECTURAL NOTE (read this before running):
#
# Your Lakehouse's SQL Analytics Endpoint (auto-created alongside the
# Lakehouse in script 02) is READ-ONLY — Fabric auto-mirrors Spark-written
# Delta tables there for querying, but dbt cannot CREATE TABLEs through it.
# This is documented in dbt_Project_Reference_and_Fabric_Setup.md from
# earlier in this program.
#
# So this script creates a SEPARATE Fabric Warehouse item — the officially
# supported target for dbt to actually WRITE Gold-layer tables via T-SQL —
# and returns credentials for BOTH:
#   - the Lakehouse SQL endpoint (read-only — good for querying Bronze/Silver
#     data that Spark notebooks already wrote)
#   - the new Warehouse (read/write — what your profiles.yml should target)
# =============================================================================
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/fabric_api_helpers.sh"

if [[ ! -f "./fabric_environment.env" ]]; then
  echo "ERROR: fabric_environment.env not found. Run scripts 01-03 first." >&2
  exit 1
fi
# shellcheck disable=SC1091
source ./fabric_environment.env

WAREHOUSE_NAME="oaktree_trades_wh"

echo "=============================================================="
echo " Creating a Fabric Warehouse (for dbt writes) + gathering credentials"
echo "=============================================================="

echo ">> [1/4] Creating the Warehouse..."
TOKEN=$(fabric_token)
WAREHOUSES_JSON=$(curl -s -H "Authorization: Bearer ${TOKEN}" \
  "${FABRIC_API_BASE}/workspaces/${WORKSPACE_ID}/warehouses")
WAREHOUSE_ID=$(echo "${WAREHOUSES_JSON}" | python3 -c 'import json,sys; data=json.load(sys.stdin); print(next((item.get("id", "") for item in data.get("value", []) if item.get("displayName") == sys.argv[1]), ""))' "${WAREHOUSE_NAME}")

if [[ -n "${WAREHOUSE_ID}" && "${WAREHOUSE_ID}" != "null" ]]; then
  echo "   Existing Warehouse found; reusing it."
else
  WAREHOUSE_JSON=$(fabric_api_call POST "/workspaces/${WORKSPACE_ID}/warehouses" \
    "{\"displayName\": \"${WAREHOUSE_NAME}\"}")
  WAREHOUSE_ID=$(echo "${WAREHOUSE_JSON}" | python3 -c 'import json,sys; v=json.load(sys.stdin).get("id"); print(v or "")')

  if [[ -z "${WAREHOUSE_ID}" || "${WAREHOUSE_ID}" == "null" ]]; then
    WAREHOUSES_JSON=$(curl -s -H "Authorization: Bearer ${TOKEN}" \
      "${FABRIC_API_BASE}/workspaces/${WORKSPACE_ID}/warehouses")
    WAREHOUSE_ID=$(echo "${WAREHOUSES_JSON}" | python3 -c 'import json,sys; data=json.load(sys.stdin); print(next((item.get("id", "") for item in data.get("value", []) if item.get("displayName") == sys.argv[1]), ""))' "${WAREHOUSE_NAME}")
  fi
fi

if [[ -z "${WAREHOUSE_ID}" || "${WAREHOUSE_ID}" == "null" ]]; then
  echo "ERROR: Warehouse creation did not return an id. Full response:" >&2
  echo "${WAREHOUSE_JSON:-${WAREHOUSES_JSON}}" >&2
  exit 1
fi
echo "   Warehouse ID: ${WAREHOUSE_ID}"

echo ">> [2/4] Fetching the Warehouse's SQL connection string (read/write)..."
WAREHOUSE_DETAILS=$(curl -s -H "Authorization: Bearer ${TOKEN}" \
  "${FABRIC_API_BASE}/workspaces/${WORKSPACE_ID}/warehouses/${WAREHOUSE_ID}")
# WAREHOUSE_CONNECTION_STRING=$(echo "${WAREHOUSE_DETAILS}" | jq -r '.properties.connectionString')
WAREHOUSE_CONNECTION_STRING=$(echo "${WAREHOUSE_DETAILS}" | python3 -c 'import json,sys; print(json.load(sys.stdin).get("properties",{}).get("connectionString",""))')
echo "   Warehouse connection string: ${WAREHOUSE_CONNECTION_STRING}"

echo ">> [3/4] Fetching the Lakehouse's SQL Analytics Endpoint (read-only, for reference)..."
LAKEHOUSE_DETAILS=$(curl -s -H "Authorization: Bearer ${TOKEN}" \
  "${FABRIC_API_BASE}/workspaces/${WORKSPACE_ID}/lakehouses/${LAKEHOUSE_ID}")
# LAKEHOUSE_SQL_ENDPOINT=$(echo "${LAKEHOUSE_DETAILS}" | jq -r '.properties.sqlEndpointProperties.connectionString')
LAKEHOUSE_SQL_ENDPOINT=$(echo "${LAKEHOUSE_DETAILS}" | python3 -c 'import json,sys; print(json.load(sys.stdin).get("properties",{}).get("sqlEndpointProperties",{}).get("connectionString",""))')
echo "   Lakehouse SQL endpoint (READ-ONLY): ${LAKEHOUSE_SQL_ENDPOINT}"

echo ">> [4/4] Generating dbt profiles.yml targeting the Warehouse..."
mkdir -p ./dbt_fabric_output
cat > ./dbt_fabric_output/profiles.yml <<EOF
# Generated by 04_create_warehouse_and_get_dbt_creds.sh
# Copy this into your dbt project (or point DBT_PROFILES_DIR at this folder).
#
# Uses 'authentication: CLI' -- this means whoever runs dbt must have an
# active 'az login' session with access to this workspace. For a shared /
# CI environment, replace this block with a service-principal-based
# authentication method instead (see dbt-fabric's own docs for the exact
# keys, as this is the one area most likely to differ by organization).

oaktree_dbt:
  target: fabric-dev
  outputs:
    fabric-dev:
      type: fabric
      authentication: CLI
      driver: "ODBC Driver 18 for SQL Server"
      host: "${WAREHOUSE_CONNECTION_STRING}"
      database: "${WAREHOUSE_NAME}"
      schema: dbo
      threads: 4
EOF

cat >> "./fabric_environment.env" <<EOF
WAREHOUSE_NAME=${WAREHOUSE_NAME}
WAREHOUSE_ID=${WAREHOUSE_ID}
WAREHOUSE_CONNECTION_STRING=${WAREHOUSE_CONNECTION_STRING}
LAKEHOUSE_SQL_ENDPOINT_READONLY=${LAKEHOUSE_SQL_ENDPOINT}
EOF

echo "=============================================================="
echo " DONE. Everything is provisioned."
echo ""
echo " ---- CREDENTIALS / CONNECTION DETAILS ----"
echo " Warehouse (READ/WRITE -- point dbt here):"
echo "   ${WAREHOUSE_CONNECTION_STRING}"
echo " Lakehouse SQL Endpoint (READ-ONLY -- query only, dbt cannot write here):"
echo "   ${LAKEHOUSE_SQL_ENDPOINT}"
echo ""
echo " A ready-to-use dbt profiles.yml was written to:"
echo "   ./dbt_fabric_output/profiles.yml"
echo ""
echo " NEXT STEPS TO START DBT:"
echo "   1. az login   (if your session has expired)"
echo "   2. pip install dbt-fabric"
echo "   3. Copy your project's models/seeds/etc. next to this profiles.yml,"
echo "      or set: export DBT_PROFILES_DIR=\$(pwd)/dbt_fabric_output"
echo "   4. dbt debug   (confirms the connection works before you run anything)"
echo "   5. dbt seed && dbt run && dbt test   (exactly as you did locally)"
echo "=============================================================="
